### ISSUE TITLE
Add all fields in Telegram User

### ISSUE THREAD

**Issue by OlegNovosad** [khamidjon-khamidov/flutter_telegram_web_app#11]
Currently telegram user does not have all fields received from init data (which is `WebAppInitData`.  This includes:

1. Add `isBot`, `isPremium`, `addedToAttachmentMenu`, `photoUrl`
2. Move `TelegramUser` to separate file.
3. Make `WebAppUser` internal
4. FIx fields naming and optionality (e.g. `first_name` is not optional)

**Comment by khamidjon-khamidov** [comment]
@OlegNovosad `TelegramUser` (and TelegramInitData) is custom model generated from validation data which does not contain photoUrl, isPremium, etc.. WebAppInitData has user field (`WebAppUser`) which already contains those fields. But you are right that new model should be created and WebAppUser should be internal.

**Comment by khamidjon-khamidov** [comment]
I am closing this task as I already created new task for creating new model for WebAppUser
