### ISSUE TITLE
Cache question

### ISSUE THREAD

**Issue by otopba** [khamidjon-khamidov/flutter_telegram_web_app#16]
Hello!

Thank you for the package. Have you encountered the issue where Telegram caches a mini app, and even if you deploy a new version, the old one still opens?

If so, could you please tell me how you solve this?

**Comment by khamidjon-khamidov** [comment]
Hi @otopba. Thanks for raising the issue! For iOS and mac, it is hard to clear the cache. For me, it always works when I use different account or wait for a few days.

In Android, if you open the app, press menu button and reload couple of times, it works almost all the time. 

If you are developing telegram specific feature and need to reload every time, [this](https://core.telegram.org/bots/webapps#testing-mini-apps ) should be a good option using android.

**Comment by OlegNovosad** [comment]
@otopba 

On iOS devices when you tap 10 times fast on your account there is an option `Clear webview cache` along with debugging webview. 

You can also find more info on testing here: https://core.telegram.org/bots/webapps#testing-mini-apps

**Comment by otopba** [comment]
Thanks!
