### ISSUE TITLE
How to prevent the app close when swipe/scroll down?

### ISSUE THREAD

**Issue by farshid-shokrolahi** [khamidjon-khamidov/flutter_telegram_web_app#19]
I'm experiencing an issue where the app closes whenever a user scrolls down, even on scrollable content. I'm not sure if this is a bug with Telegram or Flutter. Despite testing all available solutions online, I haven't been able to resolve the problem on both Android and iOS devices. Do you have any suggestions on how to fix this? If this package could fix this issue in the next version, it would make many users very happy.

**Comment by khamidjon-khamidov** [comment]
@farshid-shokrolahi please check this [web app](t.me/bozorbop_bot/bozorchi?startapp=hello). I did some fix for the example app which worked for my android device. If this doesn't work for you, then I will try to find another solution

**Comment by farshid-shokrolahi** [comment]
@khamidjon-khamidov Thank you bro, the example app in lib worked.
