### ISSUE TITLE
Data-check-string

### ISSUE THREAD

**Issue by bugrevealingbme** [khamidjon-khamidov/flutter_telegram_web_app#3]
**Validating data received via the Mini App**

How do I go about checking the data?

Data-check-string is a chain of all retrieved fields, alphabetized in the format key=<value>, with the line feed character ('\n', 0x0A) used as a separator - for example, 'auth_date=<auth_date>\nquery_id=<query_id>\nuser=<user>'.

how can I get this?

**Comment by bugrevealingbme** [comment]
I've been trying for hours and I haven't been able to verify this data. Fuck Telegram

**Comment by khamidjon-khamidov** [comment]
@bugrevealingbme The string is in `TelegramWebApp.instance.initData.raw`

**Comment by bugrevealingbme** [comment]
I do not have .raw

**Comment by khamidjon-khamidov** [comment]
In telegram_init_data.dart file, there is TelegramInitData class which contains `raw` in the library. You can access this variable via `TelegramWebApp.instance.initData.raw`. But this is not sorted fields (it is just what is provided by telegram in the web app. When backend receives it, backend should decode, sort and remove hash field. Then calculate hashes.

**Comment by bugrevealingbme** [comment]
<img width="709" alt="Ekran Resmi 2024-06-18 17 04 44" src="https://github.com/khamidjon-khamidov/flutter_telegram_web_app/assets/22865739/4f7d2cdc-2309-4aad-ae5b-f5f0a0fd85d1">

Am I using the wrong package or is it the old version in pub.dev?
https://pub.dev/packages/telegram_web_app

**Comment by khamidjon-khamidov** [comment]
@bugrevealingbme Sorry forgot to update with my local changes. Please check `telegram_web_app 0.1.2 `

**Comment by bugrevealingbme** [comment]
```
return TelegramInitData(
      user: user,
      chatInstance: chatInstance,
      chatType: chatType,
      authDate: authDate,
      hash: hash,
      raw: data,
    );
```

use

`raw: rawData,`

otherwise it bugs my app

**Comment by bugrevealingbme** [comment]
not sure what changed but the plugin is broken

**Comment by bugrevealingbme** [comment]
![IMG_713DD41B98D5-1](https://github.com/khamidjon-khamidov/flutter_telegram_web_app/assets/22865739/61dc02f3-9bf9-4583-9d03-0153d60a0aba)

**Comment by bugrevealingbme** [comment]
I downgraded and the problem was solved. I think this plugin is very important, could you please test it on the release version before you release it?

**Comment by khamidjon-khamidov** [comment]
Great thanks). We are using this plugin in our production software. But I will try to test every time

**Comment by bugrevealingbme** [comment]
Thank you, I am waiting for the new version. Also, does the start_param value work in version 0.1.0? I couldn't get it for some reason, how exactly do I use it?

**Comment by khamidjon-khamidov** [comment]
You can ask topics in @flutter_telegram telegram channel.

Could you provide reproducing steps when the new version is causing the issue? As I said, latest version in my production code is working fine. 

Regarding start_param,  you can start mini app with param in` t.me/{botUsername}/{miniAppName}?startapp={param}.` For example:` t.me/bozorbop_bot/bozorchi?startapp=m402`. You can access the variable via `WebAppInitData::{start_param}`. 

There is another field tgWebAppStartParam with same functionality. But there is a known issue with this.

**Comment by bugrevealingbme** [comment]
I don't do anything extra in the new version. Any call from TelegramWebApp.instance.initData directly breaks it.

I call start_param from initDataUnsafe but I can't get any data, the link I used: https://t.me/haw_haw_bot/theapp?start=165387110

**Comment by bugrevealingbme** [comment]
> I don't do anything extra in the new version. Any call from TelegramWebApp.instance.initData directly breaks it.
> 
> I call start_param from initDataUnsafe but I can't get any data, the link I used: https://t.me/haw_haw_bot/theapp?start=165387110

TelegramWebApp.instance.initDataUnsafe?.start_param

**Comment by bugrevealingbme** [comment]
maybe it is broken to start_param in version 0.1.0. But I can't use 0.1.2

**Comment by bugrevealingbme** [comment]
Have you tried running the package as `telegram_web_app: ^0.1.2` instead of local?

**Comment by khamidjon-khamidov** [comment]
Okay will check it today evening

**Comment by bugrevealingbme** [comment]
Thanks, I am waiting to publish my application. Thank you for the package

**Comment by khamidjon-khamidov** [comment]
I am closing this as it is resloved
