### ISSUE TITLE
Error during build

### ISSUE THREAD

**Issue by baetacoin** [khamidjon-khamidov/flutter_telegram_web_app#34]
I get several build errors each time i add this package. i have followed all instructions on the readme page but i cant run my app when this plugin is added.

../../.pub-cache/hosted/pub.dev/js-0.7.1/lib/js.dart:8:1: Error: Can't access platform private library.
export 'dart:_js_annotations'
../../.pub-cache/hosted/pub.dev/js-0.7.1/lib/js.dart:8:1: Error: Dart library 'dart:_js_annotations' is not available on this platform.
export 'dart:_js_annotations'
The unavailable library 'dart:_js_annotations' is imported through these packages:

**Comment by khamidjon-khamidov** [comment]
@baetacoin are you building it for browser? You can't build this package for other platforms

**Comment by baetacoin** [comment]
Thanks for the response. I am building for web "flutter run -d chrome" gives me such error. I created a new flutter project, added this package and it gives me this error. I don't know if there are other steps i need to follow not mentioned in the redme page

**Comment by AbbosSaidov** [comment]
I have exactly the same error in chrome

**Comment by khamidjon-khamidov** [comment]
@AbbosSaidov @baetacoin I wasn't able to reproduce the issue. Please provide reproducing steps if it still persists

**Comment by OlegNovosad** [comment]
@baetacoin @AbbosSaidov this issue will occur in case you try to include this package and run on non web platform. This is due to limitation that `js_interop` and other corresponding packages cannot be built for other platforms than web.

**Comment by khamidjon-khamidov** [comment]
This issue should have been resolved after using web package.
