### ISSUE TITLE
How can I use the latest version of Telegram BOT API?

### ISSUE THREAD

**Issue by twilight2dev** [khamidjon-khamidov/flutter_telegram_web_app#35]
Is there a way to update it to the latest version so that I can access the new functions?

Thank you!

**Comment by khamidjon-khamidov** [comment]
@twilight2dev what features you mean? **shareToStory**?

**Comment by twilight2dev** [comment]
> @twilight2dev what features you mean? **shareToStory**?

Yes sir, i need to implement that feature

**Comment by twilight2dev** [comment]
but the problem is not your lib, I can update the apis of version 7.8 myself, but I want to consult you about how I can use version 7.8 on all mobile devices, because in my case, some are 7.4 and some are 7.8

**Comment by suiebay** [comment]
> Is there a way to update it to the latest version so that I can access the new functions?
> 
> Thank you!

+1

**Comment by twilight2dev** [comment]
so please, can someone help me know "what does telegram bot api version depend on?"

**Comment by OlegNovosad** [comment]
> so please, can someone help me know "what does telegram bot api version depend on?"

I don't think we can answer that question but with the use of this library you can get the version of Telegram app of user by using `TelegramWebApp.instance.version` or make feature toggles with `isVersionAtLeast` method.
