### ISSUE TITLE
Telegram Stars

### ISSUE THREAD

**Issue by Developer1414** [khamidjon-khamidov/flutter_telegram_web_app#38]
When will you add Telegram Stars so users can make purchases?

**Comment by khamidjon-khamidov** [comment]
This library is implementation of [mini app](https://core.telegram.org/bots/webapps). Telegram stars are telegram bot feature and should be implemented in backend.

**Comment by OlegNovosad** [comment]
@Developer1414 you have to workout telegram stars on your own. This app supports all the stuff around with alerts etc., which might be helpful. Here is an example of one of mine implementations of invoice purchases, which can give you the starting point:

```dart
/// Creates an invoice URL for the given [product].
Future<String?> createInvoiceUrl(Product product) async {
  setLoading(true);

  final uri = Uri.parse("$kTelegramBaseUrl/createInvoiceLink");
  String? invoiceUrl;
  try {
    logger.i("Sending request to $uri");

    final response = await post(uri,
        headers: <String, String>{
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode({
          "title": product.title,
          "description": product.description,
          "payload": product.payload,
          "provider_token": "",
          "currency": "XTR",
          "prices": [
            {"label": product.label, "amount": product.price}
          ],
        }));

    if (response.statusCode != 200) {
      return null;
    }

    logger.i("Response: ${response.body}");

    final data = jsonDecode(response.body);
    final ok = data["ok"] as bool;

    if (!ok) {
      return null;
    }

    invoiceUrl = data["result"] as String;
  } catch (e, stackTrace) {
    logger.e(e, stackTrace: stackTrace);
  }

  setLoading(false);

  return invoiceUrl;
}
```

- `Product` is a custom class I've added for managing products within db
- `kTelegramBaseUrl` is generally a bot url

Then you can use the method from these apis: `telegram.openInvoice(...)` to continue.

**Comment by Developer1414** [comment]
> @Developer1414 you have to workout telegram stars on your own. This app supports all the stuff around with alerts etc., which might be helpful. Here is an example of one of mine implementations of invoice purchases, which can give you the starting point:
> 
> ```dart
> /// Creates an invoice URL for the given [product].
> Future<String?> createInvoiceUrl(Product product) async {
>   setLoading(true);
> 
>   final uri = Uri.parse("$kTelegramBaseUrl/createInvoiceLink");
>   String? invoiceUrl;
>   try {
>     logger.i("Sending request to $uri");
> 
>     final response = await post(uri,
>         headers: <String, String>{
>           'Content-Type': 'application/json; charset=UTF-8',
>         },
>         body: jsonEncode({
>           "title": product.title,
>           "description": product.description,
>           "payload": product.payload,
>           "provider_token": "",
>           "currency": "XTR",
>           "prices": [
>             {"label": product.label, "amount": product.price}
>           ],
>         }));
> 
>     if (response.statusCode != 200) {
>       return null;
>     }
> 
>     logger.i("Response: ${response.body}");
> 
>     final data = jsonDecode(response.body);
>     final ok = data["ok"] as bool;
> 
>     if (!ok) {
>       return null;
>     }
> 
>     invoiceUrl = data["result"] as String;
>   } catch (e, stackTrace) {
>     logger.e(e, stackTrace: stackTrace);
>   }
> 
>   setLoading(false);
> 
>   return invoiceUrl;
> }
> ```
> 
> * `Product` is a custom class I've added for managing products within db
> * `kTelegramBaseUrl` is generally a bot url
> 
> Then you can use the method from these apis: `telegram.openInvoice(...)` to continue.

Thanks a lot!
