### ISSUE TITLE
Flutter 3.27 issue

### ISSUE THREAD

**Issue by otopba** [khamidjon-khamidov/flutter_telegram_web_app#58]
Target dart2js failed: ProcessException: Process exited abnormally with exit code 1:
../lib/src/flutter/events/location_requested_event.dart:9:65:
Error: Function converted via 'toJS' contains invalid types in its function signature: 'void Function(*LocationData*)'.
      : super(TelegramEventType.locationRequested, eventHandler.toJS);
                                                                ^
../lib/src/js/telegram/src/models/bottom_button_params.dart:10:10:
Warning: Initializers for parameters are ignored on static interop external functions.
    bool isActive = false,
         ^
../lib/src/js/telegram/src/models/bottom_button_params.dart:11:10:
Warning: Initializers for parameters are ignored on static interop external functions.
    bool isVisible = true,
         ^
Error: Compilation failed.

**Comment by HosseinAsadi** [comment]
I have the same problem. :(
